### ISSUE TITLE
Build result in gitlab CI is showing "%20" instead of normal spaces

### ISSUE THREAD

**Issue by alvinthen** [virtualmarc/gitlab-ci-runner-win#27]
For example, in the build result page in GitLab CI, it shows
C%3A%20%26%26%20cd%20C%3A%5CGitLab-CI-Runner%5Cprojects%5Cproject-1%20%26%26%20git%20reset%20--hard%20%26%26%20git%20clean%20-f%20%26%26%20git%20fetch

**Comment by sschuberth** [comment]
So shouldn't this be closed by now?
